import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  AKANE_SERVICE_NAME,
  AKANE_STAGE_IDS,
} from "./constants.js";
import type {
  AkaneConfig,
  AkaneStageId,
  AkaneStageState,
  AkaneState,
  ArtifactWriteMode,
} from "./types.js";

function nowIso(): string {
  return new Date().toISOString();
}

function stageTitle(stage: AkaneStageId): string {
  return stage
    .split("-")
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(" ");
}

function defaultStageTemplate(stage: AkaneStageId): string {
  return `# ${stageTitle(stage)}\n\nGenerated by ${AKANE_SERVICE_NAME}.\n`;
}

export function resolveProjectRoot(input: {
  directory: string;
  worktree?: string;
  projectRoot?: string;
}): string {
  if (input.projectRoot && input.projectRoot.trim()) {
    return path.resolve(input.projectRoot);
  }

  if (input.worktree && input.worktree.trim()) {
    return path.resolve(input.worktree);
  }

  return path.resolve(input.directory);
}

export function resolveArtifactDir(
  projectRoot: string,
  config: AkaneConfig,
): string {
  if (path.isAbsolute(config.artifacts.dir)) {
    return config.artifacts.dir;
  }

  return path.join(projectRoot, config.artifacts.dir);
}

export function resolveStatePath(
  projectRoot: string,
  config: AkaneConfig,
): string {
  return path.join(resolveArtifactDir(projectRoot, config), config.artifacts.stateFile);
}

export function resolveStageArtifactPath(
  projectRoot: string,
  config: AkaneConfig,
  stage: AkaneStageId,
): string {
  return path.join(resolveArtifactDir(projectRoot, config), config.artifacts.files[stage]);
}

export function createInitialState(input: {
  config: AkaneConfig;
  configPath: string;
  projectRoot: string;
}): AkaneState {
  const artifactDir = resolveArtifactDir(input.projectRoot, input.config);
  const timestamp = nowIso();

  const stages = Object.fromEntries(
    AKANE_STAGE_IDS.map((stage) => [
      stage,
      {
        path: resolveStageArtifactPath(input.projectRoot, input.config, stage),
        status: "pending",
        updatedAt: null,
      },
    ]),
  ) as AkaneState["stages"];

  return {
    version: input.config.version,
    serviceName: input.config.serviceName,
    configPath: input.configPath,
    projectRoot: input.projectRoot,
    artifactDir,
    initializedAt: timestamp,
    updatedAt: timestamp,
    activeStage: null,
    stageOrder: [...input.config.workflow.stageOrder],
    stages,
    roles: { ...input.config.roles },
  };
}

async function readStateFile(statePath: string): Promise<AkaneState | null> {
  try {
    const raw = await readFile(statePath, "utf8");
    return JSON.parse(raw) as AkaneState;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return null;
    }

    throw error;
  }
}

async function writeStateFile(statePath: string, state: AkaneState): Promise<void> {
  await writeFile(statePath, JSON.stringify(state, null, 2) + "\n", "utf8");
}

export async function ensureArtifactLayout(input: {
  projectRoot: string;
  config: AkaneConfig;
  configPath: string;
  force?: boolean;
}): Promise<{
  artifactDir: string;
  statePath: string;
  state: AkaneState;
  createdFiles: string[];
}> {
  const artifactDir = resolveArtifactDir(input.projectRoot, input.config);
  const statePath = resolveStatePath(input.projectRoot, input.config);
  const createdFiles: string[] = [];

  await mkdir(artifactDir, { recursive: true });

  for (const stage of AKANE_STAGE_IDS) {
    const artifactPath = resolveStageArtifactPath(input.projectRoot, input.config, stage);
    try {
      if (input.force) {
        throw Object.assign(new Error("force"), { code: "ENOENT" });
      }

      await readFile(artifactPath, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
        throw error;
      }

      await writeFile(artifactPath, defaultStageTemplate(stage), "utf8");
      createdFiles.push(artifactPath);
    }
  }

  let state = await readStateFile(statePath);
  if (!state || input.force) {
    state = createInitialState({
      config: input.config,
      configPath: input.configPath,
      projectRoot: input.projectRoot,
    });

    for (const stage of AKANE_STAGE_IDS) {
      state.stages[stage].status = "initialized";
      state.stages[stage].updatedAt = state.initializedAt;
    }

    await writeStateFile(statePath, state);
    createdFiles.push(statePath);
  }

  return { artifactDir, statePath, state, createdFiles };
}

export async function writeStageArtifact(input: {
  projectRoot: string;
  config: AkaneConfig;
  configPath: string;
  stage: AkaneStageId;
  content: string;
  mode: ArtifactWriteMode;
  details?: Partial<Omit<AkaneStageState, "path" | "status" | "updatedAt">>;
}): Promise<{
  artifactDir: string;
  artifactPath: string;
  statePath: string;
  state: AkaneState;
}> {
  const ensured = await ensureArtifactLayout({
    projectRoot: input.projectRoot,
    config: input.config,
    configPath: input.configPath,
  });

  const artifactPath = resolveStageArtifactPath(
    input.projectRoot,
    input.config,
    input.stage,
  );
  const previous =
    input.mode === "append"
      ? await readFile(artifactPath, "utf8").catch((error: NodeJS.ErrnoException) =>
          error.code === "ENOENT" ? "" : Promise.reject(error),
        )
      : "";
  const nextContent =
    input.mode === "append"
      ? `${previous}${previous.endsWith("\n") || !previous ? "" : "\n"}${input.content}\n`
      : `${input.content}${input.content.endsWith("\n") ? "" : "\n"}`;

  await writeFile(artifactPath, nextContent, "utf8");

  const state = ensured.state;
  const timestamp = nowIso();
  state.activeStage = input.stage;
  state.updatedAt = timestamp;
  state.stages[input.stage] = {
    path: artifactPath,
    status: "completed",
    updatedAt: timestamp,
    ...input.details,
  };

  await writeStateFile(ensured.statePath, state);

  return {
    artifactDir: ensured.artifactDir,
    artifactPath,
    statePath: ensured.statePath,
    state,
  };
}
